import { Route } from '../models/route';

/**
 * Exports discovered routes to JSON or OpenAPI 3.0 format.
 *
 * Pure functions with no VS Code dependencies, making them easily testable.
 */
export class RouteExporter {
  /**
   * Exports routes as a pretty-printed JSON array.
   */
  static toJson(routes: Route[]): string {
    const cleaned = routes.map((r) => ({
      method: r.method,
      path: r.path,
      filePath: r.filePath,
      lineNumber: r.lineNumber,
      framework: r.framework,
    }));
    return JSON.stringify(cleaned, null, 2);
  }

  /**
   * Exports routes as an OpenAPI 3.0 specification stub.
   * @param routes   The routes to export.
   * @param asJson   If true, returns JSON; otherwise returns YAML.
   */
  static toOpenApi(routes: Route[], asJson = false): string {
    const paths: Record<string, Record<string, object>> = {};

    for (const route of routes) {
      const pathKey = route.path.replace(/:(\w+)/g, '{$1}');
      if (!paths[pathKey]) {
        paths[pathKey] = {};
      }

      const methods = route.method === 'ALL'
        ? ['get', 'post', 'put', 'delete', 'patch']
        : [route.method.toLowerCase()];

      for (const method of methods) {
        if (!paths[pathKey][method]) {
          paths[pathKey][method] = {
            summary: `${route.method} ${route.path}`,
            responses: {
              '200': { description: 'Successful response' },
            },
          };
        }
      }
    }

    const spec = {
      openapi: '3.0.3',
      info: {
        title: 'API Routes (generated by APICompass)',
        version: '1.0.0',
      },
      paths,
    };

    if (asJson) {
      return JSON.stringify(spec, null, 2);
    }

    return this.toYaml(spec);
  }

  /**
   * Minimal YAML serialiser sufficient for the OpenAPI spec structure.
   * Avoids adding a dependency on a YAML library.
   */
  private static toYaml(obj: unknown, indent = 0): string {
    const prefix = '  '.repeat(indent);

    if (obj === null || obj === undefined) {
      return 'null';
    }

    if (typeof obj === 'string') {
      if (/[:{}\[\],&*?|>!%#@`'"]/.test(obj) || obj === '') {
        return `'${obj.replace(/'/g, "''")}'`;
      }
      return obj;
    }

    if (typeof obj === 'number' || typeof obj === 'boolean') {
      return String(obj);
    }

    if (Array.isArray(obj)) {
      if (obj.length === 0) {
        return '[]';
      }
      return obj
        .map((item) => {
          const value = this.toYaml(item, indent + 1);
          if (typeof item === 'object' && item !== null) {
            const lines = value.split('\n');
            return `${prefix}- ${lines[0].trim()}\n${lines.slice(1).join('\n')}`;
          }
          return `${prefix}- ${value}`;
        })
        .join('\n');
    }

    if (typeof obj === 'object') {
      const entries = Object.entries(obj as Record<string, unknown>);
      if (entries.length === 0) {
        return '{}';
      }
      return entries
        .map(([key, value]) => {
          if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
            const nested = this.toYaml(value, indent + 1);
            return `${prefix}${key}:\n${nested}`;
          }
          if (Array.isArray(value)) {
            const nested = this.toYaml(value, indent + 1);
            return `${prefix}${key}:\n${nested}`;
          }
          return `${prefix}${key}: ${this.toYaml(value, indent)}`;
        })
        .join('\n');
    }

    return String(obj);
  }
}
